"""PopART-compatible NEXUS export from immutable sequence metadata.

This module deliberately does not alter the generic NEXUS exporter: PopART
traits are a presentation/interoperability concern, not a property of every
DNA NEXUS document.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import Path
import re

from core.sequence_dataset import SequenceDataset
from export.sequence_export import _validate_taxon_ids


class PopArtExportError(ValueError):
    """Raised when a dataset cannot be represented safely as PopART NEXUS."""


def export_dataset_to_popart_nexus(
    dataset: SequenceDataset,
    filepath: str | Path,
    *,
    trait_field: str,
    category_order: Sequence[str] | None = None,
    missing_values: str = "include",
) -> None:
    """Write a DNA NEXUS document with one-hot categorical ``TRAITS``.

    ``trait_field`` is resolved case/spacing-insensitively against each
    record's metadata, while values themselves are preserved as categories.
    Missing values use an all-``?`` trait vector; they are never converted to
    a false all-zero category vector.  ``missing_values='exclude'`` omits
    records with no trait value from every block.
    """

    rows, categories, trait_labels = build_popart_rows(
        dataset,
        trait_field=trait_field,
        category_order=category_order,
        missing_values=missing_values,
    )
    output = _validate_output_path(filepath)
    try:
        with output.open("w", encoding="utf-8", newline="\n") as handle:
            handle.write("#NEXUS\n")
            handle.write("[ Generated by SangerFlow: PopART trait export ]\n")
            handle.write(f"[ Trait field: {trait_field} ]\n\n")
            handle.write("BEGIN TAXA;\n")
            handle.write(f"  DIMENSIONS NTAX={len(rows)};\n  TAXLABELS\n")
            for taxon_id, _, _ in rows:
                handle.write(f"    {taxon_id}\n")
            handle.write("  ;\nEND;\n\n")
            handle.write("BEGIN DATA;\n")
            handle.write(f"  DIMENSIONS NTAX={len(rows)} NCHAR={len(rows[0][1])};\n")
            handle.write("  FORMAT DATATYPE=DNA GAP=- MISSING=?;\n  MATRIX\n")
            for taxon_id, sequence, _ in rows:
                handle.write(f"    {taxon_id} {sequence}\n")
            handle.write("  ;\nEND;\n\n")
            handle.write("BEGIN TRAITS;\n")
            handle.write(f"  DIMENSIONS NTRAITS={len(categories)};\n")
            handle.write("  FORMAT LABELS=YES MISSING=? SEPARATOR=COMMA;\n")
            handle.write("  TRAITLABELS " + " ".join(trait_labels) + ";\n")
            handle.write("  [ Trait label mapping: " + "; ".join(
                f"{label}={category}" for label, category in zip(trait_labels, categories)
            ) + " ]\n")
            handle.write("  MATRIX\n")
            for taxon_id, _, values in rows:
                handle.write(f"    {taxon_id} {','.join(values)}\n")
            handle.write("  ;\nEND;\n")
    except OSError as error:
        raise PopArtExportError(f"unable to write PopART NEXUS: {output}") from error


def build_popart_rows(
    dataset: SequenceDataset,
    *,
    trait_field: str,
    category_order: Sequence[str] | None = None,
    missing_values: str = "include",
) -> tuple[tuple[tuple[str, str, tuple[str, ...]], ...], tuple[str, ...], tuple[str, ...]]:
    """Return validated PopART rows for preview/testing without writing a file."""

    if not isinstance(dataset, SequenceDataset):
        raise PopArtExportError("dataset must be a SequenceDataset")
    if not dataset.records:
        raise PopArtExportError("dataset must contain at least one record")
    if not dataset.is_equal_length:
        raise PopArtExportError("PopART NEXUS export requires equal-length sequences")
    if not isinstance(trait_field, str) or not trait_field.strip():
        raise PopArtExportError("trait_field must be a non-empty string")
    if missing_values not in {"include", "exclude"}:
        raise PopArtExportError("missing_values must be 'include' or 'exclude'")
    _validate_taxon_ids(record.sequence_id for record in dataset.records)

    selected: list[tuple[str, str, str | None]] = []
    for record in dataset.records:
        value = _metadata_value(record.metadata, trait_field)
        if value is None and missing_values == "exclude":
            continue
        selected.append((record.sequence_id, record.sequence, value))
    if not selected:
        raise PopArtExportError("no records remain after applying missing-value handling")

    observed = tuple(dict.fromkeys(value for _, _, value in selected if value is not None))
    categories = _resolve_categories(observed, category_order)
    if not categories:
        raise PopArtExportError("at least one non-missing trait category is required")
    labels = _trait_labels(categories)
    category_index = {category: index for index, category in enumerate(categories)}
    rows = []
    for taxon_id, sequence, value in selected:
        if value is None:
            vector = tuple("?" for _ in categories)
        else:
            vector = tuple("1" if index == category_index[value] else "0" for index in range(len(categories)))
        if len(vector) != len(categories):  # defensive invariant
            raise PopArtExportError("trait vector length does not match NTRAITS")
        rows.append((taxon_id, sequence, vector))
    return tuple(rows), categories, labels


def metadata_trait_fields(dataset: SequenceDataset) -> tuple[str, ...]:
    """Return dynamic, canonical metadata keys suitable for the Studio dialog."""

    if not isinstance(dataset, SequenceDataset):
        raise PopArtExportError("dataset must be a SequenceDataset")
    values: dict[str, str] = {}
    for record in dataset.records:
        for key in record.metadata:
            if isinstance(key, str) and key.strip():
                values.setdefault(_canonical_key(key), key)
    return tuple(values[key] for key in sorted(values))


def _metadata_value(metadata: Mapping[str, object], trait_field: str) -> str | None:
    target = _canonical_key(trait_field)
    matches = [value for key, value in metadata.items() if isinstance(key, str) and _canonical_key(key) == target]
    if len(matches) > 1:
        raise PopArtExportError(f"record has ambiguous metadata values for trait_field: {trait_field}")
    if not matches or matches[0] is None or not str(matches[0]).strip():
        return None
    value = matches[0]
    if isinstance(value, (list, tuple, set, dict)):
        raise PopArtExportError("PopART trait values must be a single categorical value")
    return str(value).strip()


def _resolve_categories(observed: tuple[str, ...], category_order: Sequence[str] | None) -> tuple[str, ...]:
    if category_order is None:
        return observed
    if isinstance(category_order, (str, bytes)):
        raise PopArtExportError("category_order must be a sequence of category strings")
    supplied = tuple(str(value).strip() for value in category_order)
    if not supplied or any(not value for value in supplied) or len(set(supplied)) != len(supplied):
        raise PopArtExportError("category_order must contain unique non-empty categories")
    if set(supplied) != set(observed):
        raise PopArtExportError("category_order must contain exactly the observed categories")
    return supplied


def _trait_labels(categories: tuple[str, ...]) -> tuple[str, ...]:
    labels = tuple(_safe_trait_label(category) for category in categories)
    if any(not label for label in labels):
        raise PopArtExportError("trait labels must contain at least one safe character")
    if len(set(labels)) != len(labels):
        raise PopArtExportError("normalized trait label collision; rename the source categories")
    return labels


def _safe_trait_label(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", value.strip()).strip("_")


def _canonical_key(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", value.strip().lower()).strip("_")


def _validate_output_path(filepath: str | Path) -> Path:
    if not isinstance(filepath, (str, Path)):
        raise PopArtExportError("filepath must be a path string or Path")
    output = Path(filepath)
    if not output.name or output.suffix.lower() not in {".nex", ".nexus"}:
        raise PopArtExportError("filepath must use a .nex or .nexus extension")
    if output.exists() and output.is_dir():
        raise PopArtExportError("filepath must refer to a file")
    if not output.parent.is_dir():
        raise PopArtExportError("filepath parent directory does not exist")
    return output
